#pragma once

#include <stdint.h>


/*
    Constants
*/

static const uint8_t ptp_version = 0x12;
static const uint16_t ptp_sdo_id = 0xffd;
static const uint8_t ptp_domain = 128;

enum ptp_message_type {
    PTP_MESSAGE_TYPE_SYNC = 0x0,
    PTP_MESSAGE_TYPE_DELAY_REQUEST = 0x1,
    PTP_MESSAGE_TYPE_PDELAY_REQUEST = 0x2,
    PTP_MESSAGE_TYPE_PDELAY_RESPONSE = 0x3,
    PTP_MESSAGE_TYPE_FOLLOW_UP = 0x8,
    PTP_MESSAGE_TYPE_DELAY_RESPONSE = 0x9,
    PTP_MESSAGE_TYPE_PDELAY_RESPONSE_FOLLOW_UP = 0xa,
    PTP_MESSAGE_TYPE_ANNOUNCE = 0xb,
    PTP_MESSAGE_TYPE_SIGNALING = 0xc,
    PTP_MESSAGE_TYPE_MANAGEMENT = 0xd,
};

enum ptp_tlv_type {
    PTP_TLV_TYPE_MANAGEMENT = 0x1,
    PTP_TLV_TYPE_MANAGEMENT_ERROR_STATUS = 0x2,
    PTP_TLV_TYPE_ORGANIZATION_EXTENSION = 0x3,
    PTP_TLV_TYPE_REQUEST_UNICAST_TRANSMISSION = 0x4,
    PTP_TLV_TYPE_GRANT_UNICAST_TRANSMISSION = 0x5,
    PTP_TLV_TYPE_CANCEL_UNICAST_TRANSMISSION = 0x6,
    PTP_TLV_TYPE_ACKNOWLEDGE_CANCEL_UNICAST_TRANSMISSION = 0x7,
    PTP_TLV_TYPE_PATH_TRACE = 0x8,
    PTP_TLV_TYPE_ALTERNATE_TIME_OFFSET_INDICATOR = 0x9,
    PTP_TLV_TYPE_ORGANIZATION_EXTENSION_PROPAGATE = 0x4000,
    PTP_TLV_TYPE_ENHANCED_ACCURACY_METRICS = 0x4001,
    PTP_TLV_TYPE_ORGANIZATION_EXTENSION_DO_NOT_PROPAGATE = 0x8000,
    PTP_TLV_TYPE_L1_SYNC = 0x8001,
    PTP_TLV_TYPE_PORT_COMMUNICATION_AVAILABILITY = 0x8002,
    PTP_TLV_TYPE_PROTOCOL_ADDRESS = 0x8003,
    PTP_TLV_TYPE_SLAVE_RX_SYNC_TIMING_DATA = 0x8004,
    PTP_TLV_TYPE_SLAVE_RX_SYNC_COMPUTED_DATA = 0x8005,
    PTP_TLV_TYPE_SLAVE_TX_EVENT_TIMESTAMPS = 0x8006,
    PTP_TLV_TYPE_CUMULATIVE_RATE_RATIO = 0x8007,
    PTP_TLV_TYPE_PAD = 0x8008,
    PTP_TLV_TYPE_AUTHENTICATION = 0x8009,
};

enum ptp_flag {
    PTP_FLAG_ALTERNATE_MASTER = 1 << 0,
    PTP_FLAG_TWO_STEP = 1 << 1,
    PTP_FLAG_UNICAST = 1 << 2,
    PTP_FLAG_PROFILE_SPECIFIC_1 = 1 << 5,
    PTP_FLAG_PROFILE_SPECIFIC_2 = 1 << 6,
    PTP_FLAG_LEAP_61 = 1 << 8,
    PTP_FLAG_LEAP_59 = 1 << 9,
    PTP_FLAG_TIMESCALE = 1 << 10,
    PTP_FLAG_CURRENT_UTC_OFFSET_VALID = 1 << 11,
    PTP_FLAG_TIME_TRACABLE = 1 << 12,
    PTP_FLAG_FREQUENCY_TRACABLE = 1 << 13,
    PTP_FLAG_SYNCHRONIZATION_UNCERTAIN = 1 << 14,
    PTP_FLAG_MASK = (1 << 15) - 1,
};

enum ptp_management_action {
    PTP_MANAGEMENT_ACTION_GET = 0x0,
    PTP_MANAGEMENT_ACTION_SET = 0x1,
    PTP_MANAGEMENT_ACTION_RESPONSE = 0x2,
    PTP_MANAGEMENT_ACTION_COMMAND = 0x3,
    PTP_MANAGEMENT_ACTION_ACKNOWLEDGE = 0x4,
};

enum ptp_management_id {
    PTP_MANAGEMENT_ID_NULL = 0x0, 
    PTP_MANAGEMENT_ID_CLOCK_DESCRIPTION = 0x1,
    PTP_MANAGEMENT_ID_USER_DESCRIPTION = 0x2,
    PTP_MANAGEMENT_ID_SAVE_IN_NON_VOLATILE_STORAGE = 0x3,
    PTP_MANAGEMENT_ID_RESET_NON_VOLATILE_STORAGE = 0x4,
    PTP_MANAGEMENT_ID_INITIALIZE = 0x5,
    PTP_MANAGEMENT_ID_FAULT_LOG = 0x6,
    PTP_MANAGEMENT_ID_FAULT_LOG_RESET = 0x7,
    PTP_MANAGEMENT_ID_DEFAULT_DATA_SET = 0x2000,
    PTP_MANAGEMENT_ID_CURRENT_DATA_SET = 0x2001,
    PTP_MANAGEMENT_ID_PARENT_DATA_SET = 0x2002,
    PTP_MANAGEMENT_ID_TIME_PROPERTIES_DATA_SET = 0x2003,
    PTP_MANAGEMENT_ID_PORT_DATA_SET = 0x2004,
    PTP_MANAGEMENT_ID_PRIORITY1 = 0x2005,
    PTP_MANAGEMENT_ID_PRIORITY2 = 0x2006,
    PTP_MANAGEMENT_ID_DOMAIN = 0x2007,
    PTP_MANAGEMENT_ID_SLAVE_ONLY = 0x2008,
    PTP_MANAGEMENT_ID_LOG_ANNOUNCE_INTERVAL = 0x2009,
    PTP_MANAGEMENT_ID_ANNOUNCE_RECEIPT_TIMEOUT = 0x200A,
    PTP_MANAGEMENT_ID_LOG_SYNC_INTERVAL = 0x200B,
    PTP_MANAGEMENT_ID_VERSION_NUMBER = 0x200C,
    PTP_MANAGEMENT_ID_ENABLE_PORT = 0x200D,
    PTP_MANAGEMENT_ID_DISABLE_PORT = 0x200E,
    PTP_MANAGEMENT_ID_TIME = 0x200F,
    PTP_MANAGEMENT_ID_CLOCK_ACCURACY = 0x2010,
    PTP_MANAGEMENT_ID_UTC_PROPERTIES = 0x2011,
    PTP_MANAGEMENT_ID_TRACEABILITY_PROPERTIES = 0x2012,
    PTP_MANAGEMENT_ID_TIMESCALE_PROPERTIES = 0x2013,
    PTP_MANAGEMENT_ID_UNICAST_NEGOTIATION_ENABLE = 0x2014,
    PTP_MANAGEMENT_ID_PATH_TRACE_LIST = 0x2015,
    PTP_MANAGEMENT_ID_PATH_TRACE_ENABLE = 0x2016,
    PTP_MANAGEMENT_ID_GRANDMASTER_CLUSTER_TABLE = 0x2017,
    PTP_MANAGEMENT_ID_UNICAST_MASTER_TABLE = 0x2018,
    PTP_MANAGEMENT_ID_UNICAST_MASTER_MAX_TABLE_SIZE = 0x2019,
    PTP_MANAGEMENT_ID_ACCEPTABLE_MASTER_TABLE = 0x201A,
    PTP_MANAGEMENT_ID_ACCEPTABLE_MASTER_TABLE_ENABLED = 0x201B,
    PTP_MANAGEMENT_ID_ACCEPTABLE_MASTER_MAX_TABLE_SIZE = 0x201C,
    PTP_MANAGEMENT_ID_ALTERNATE_MASTER = 0x201D,
    PTP_MANAGEMENT_ID_ALTERNATE_TIME_OFFSET_ENABLE = 0x201E,
    PTP_MANAGEMENT_ID_ALTERNATE_TIME_OFFSET_NAME = 0x201F,
    PTP_MANAGEMENT_ID_ALTERNATE_TIME_OFFSET_MAX_KEY = 0x2020,
    PTP_MANAGEMENT_ID_ALTERNATE_TIME_OFFSET_PROPERTIES = 0x2021,
    PTP_MANAGEMENT_ID_EXTERNAL_PORT_CONFIGURATION_ENABLED = 0x3000,
    PTP_MANAGEMENT_ID_MASTER_ONLY = 0x3001,
    PTP_MANAGEMENT_ID_HOLDOVER_UPGRADE_ENABLE = 0x3002,
    PTP_MANAGEMENT_ID_EXT_PORT_CONFIG_PORT_DATA_SET = 0x3003,
    PTP_MANAGEMENT_ID_TRANSPARENT_CLOCK_DEFAULT_DATA_SET = 0x4000,
    PTP_MANAGEMENT_ID_TRANSPARENT_CLOCK_PORT_DATA_SET = 0x4001,
    PTP_MANAGEMENT_ID_PRIMARY_DOMAIN = 0x4002,
    PTP_MANAGEMENT_ID_DELAY_MECHANISM = 0x6000,
    PTP_MANAGEMENT_ID_LOG_MIN_PDELAY_REQ_INTERVAL = 0x6001,
    PTP_MANAGEMENT_ID_IMPLEMENTATION_SPECIFIC = 0xC000,
    PTP_MANAGEMENT_ID_PROFILE_SPECIFIC = 0xE000,
};

enum ptp_management_error_id {
    PTP_MANAGEMENT_ERROR_ID_RESPONSE_TOO_BIG = 0x1,
    PTP_MANAGEMENT_ERROR_ID_NO_SUCH_ID = 0x2,
    PTP_MANAGEMENT_ERROR_ID_WRONG_LENGTH = 0x3,
    PTP_MANAGEMENT_ERROR_ID_WRONG_VALUE = 0x4,
    PTP_MANAGEMENT_ERROR_ID_NOT_SETABLE = 0x5,
    PTP_MANAGEMENT_ERROR_ID_NOT_SUPPORTED = 0x6,
    PTP_MANAGEMENT_ERROR_ID_UNPOPULATED = 0x7,
    PTP_MANAGEMENT_ERROR_ID_IMPLEMENTATION_SPECIFIC = 0xC000,
    PTP_MANAGEMENT_ERROR_ID_PROFILE_SPECIFIC = 0xE000,
    PTP_MANAGEMENT_ERROR_ID_GENERAL = 0xFFFE,
};

enum ptp_clock_class {
    PTP_CLOCK_CLASS_PRIMARY_REFERENCE = 6,
    PTP_CLOCK_CLASS_PRIMARY_REFERENCE_ALT = 7,
    PTP_CLOCK_CLASS_PRIMARY_REFERENCE_DEG = 52,
    PTP_CLOCK_CLASS_APPLICATION_SPECIFIC = 13,
    PTP_CLOCK_CLASS_APPLICATION_SPECIFIC_ALT = 14,
    PTP_CLOCK_CLASS_APPLICATION_SPECIFIC_DEG = 58,
};

enum ptp_clock_accuracy {
    PTP_CLOCK_ACCURACY_1_PS = 0x17,
    PTP_CLOCK_ACCURACY_2_5_PS,
    PTP_CLOCK_ACCURACY_10_PS,
    PTP_CLOCK_ACCURACY_25_PS,
    PTP_CLOCK_ACCURACY_100_PS,
    PTP_CLOCK_ACCURACY_250_PS,
    PTP_CLOCK_ACCURACY_1_NS,
    PTP_CLOCK_ACCURACY_2_5_NS,
    PTP_CLOCK_ACCURACY_10_NS,
    PTP_CLOCK_ACCURACY_25_NS,
    PTP_CLOCK_ACCURACY_100_NS,
    PTP_CLOCK_ACCURACY_250_NS,
    PTP_CLOCK_ACCURACY_1_US,
    PTP_CLOCK_ACCURACY_2_5_US,
    PTP_CLOCK_ACCURACY_10_US,
    PTP_CLOCK_ACCURACY_25_US,
    PTP_CLOCK_ACCURACY_100_US,
    PTP_CLOCK_ACCURACY_250_US,
    PTP_CLOCK_ACCURACY_1_MS,
    PTP_CLOCK_ACCURACY_2_5_MS,
    PTP_CLOCK_ACCURACY_10_MS,
    PTP_CLOCK_ACCURACY_25_MS,
    PTP_CLOCK_ACCURACY_100_MS,
    PTP_CLOCK_ACCURACY_250_MS,
    PTP_CLOCK_ACCURACY_1_S,
    PTP_CLOCK_ACCURACY_10_S,
    PTP_CLOCK_ACCURACY_GT_10_S,
};

enum ptp_time_source {
    PTP_TIME_SOURCE_ATOMIC_CLOCK = 0x10,
    PTP_TIME_SOURCE_GNSS = 0x20,
    PTP_TIME_SOURCE_TERRESTRIAL_RADIO = 0x30,
    PTP_TIME_SOURCE_SERIAL_TIME_CODE = 0x39,
    PTP_TIME_SOURCE_PTP = 0x40,
    PTP_TIME_SOURCE_NTP = 0x50,
    PTP_TIME_SOURCE_HAND_SET = 0x60,
    PTP_TIME_SOURCE_OTHER = 0x90,
    PTP_TIME_SOURCE_INTERNAL_OSCILLATOR= 0xa0,
};

enum ptp_tlv_unicast_flag {
    PTP_TLV_UNICAST_FLAG_MAINTAIN_REQUEST = 1 << 0,
    PTP_TLV_UNICAST_FLAG_MAINTAIN_GRANT = 1 << 1,
    PTP_TLV_UNICAST_FLAG_MASK = (1 << 2) - 1,
};

enum ptp_authentication_policy {
    PTP_AUTHENTICATION_POLICY_NONE = 0,
    PTP_AUTHENTICATION_POLICY_PLAIN = 1,
    PTP_AUTHENTICATION_POLICY_HMAC_128 = 2,
};
