[global]
transportSpecific 0xf
udp_ttl 64

delay_mechanism E2E
network_transport UDPv4
clockClass 248
clockAccuracy 0xFE
offsetScaledLogVariance 0xFFFF
domainNumber 128
time_stamping software
free_running 1
