services:
  syncryn1z3-checker:
    build: .
    ports:
      - 11588:8000
    environment:
      #- NUM_CORES=4
      - MONGO_ENABLED=1
      - MONGO_HOST=syncryn1z3-mongo
      - MONGO_PORT=27017
      - MONGO_USER=syncryn1z3
      - MONGO_PASSWORD=syncryn1z3
    deploy:
      resources:
        limits:
          #cpus: 4
          memory: 4G
    restart: unless-stopped
        
  # The python checkerlib requires a mongo db!
  syncryn1z3-mongo:
    image: mongo
    #ports:
    #  - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: syncryn1z3
      MONGO_INITDB_ROOT_PASSWORD: syncryn1z3
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
    restart: unless-stopped
