services:
  ptp-checker:
    build:
      dockerfile: checker/Dockerfile
      context: ..
    ports:
      - 11588:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=ptp-mongo
      - MONGO_PORT=27017
      - MONGO_USER=ptp
      - MONGO_PASSWORD=ptp
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
  # The python checkerlib requires a mongo db!
  ptp-mongo:
    image: mongo
    #ports:
    #  - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ptp
      MONGO_INITDB_ROOT_PASSWORD: ptp
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
